# Generated by Django 3.2.1 on 2024-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('drop_shoulders', 'Drop Shoulders'), ('baggy-joggers', 'Baggy Joggers'), ('baggy_shirts', 'Baggy Shirts'), ('cargo_pants', 'Cargo Pants'), ('head_wear', 'Head Wear'), ('baggy_shorts', 'Baggy Shorts')], default='drop_shoulders', max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('product_desc', models.CharField(max_length=1000)),
                ('product_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
