# Generated by Django 3.2.1 on 2024-10-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20241023_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.TextField(default='color'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.TextField(default='size'),
        ),
    ]
