# Generated by Django 3.2.1 on 2024-10-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20241023_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.TextField(),
        ),
    ]
