# Generated by Django 5.0.4 on 2024-10-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20241023_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='order',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='product',
        ),
    ]
