# Generated by Django 5.0.4 on 2024-10-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_orders_order_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('drop_shoulders', 'Drop Shoulders'), ('baggy_joggers', 'Baggy Joggers'), ('baggy_shirts', 'Baggy Shirts'), ('cargo_pants', 'Cargo Pants'), ('head_wear', 'Head Wear'), ('baggy_shorts', 'Baggy Shorts')], default='drop_shoulders', max_length=100),
        ),
    ]
