# Generated by Django 5.0.4 on 2024-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest_arrival',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('drop-shoulders', 'Drop Shoulders'), ('baggy-joggers', 'Baggy Joggers'), ('baggy-shirts', 'Baggy Shirts'), ('cargo-pants', 'Cargo Pants'), ('head-wear', 'Head Wear'), ('baggy-shorts', 'Baggy Shorts')], default='drop-shoulders', max_length=100),
        ),
    ]
