# Generated by Django 5.1.3 on 2025-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_product_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_1',
            field=models.ImageField(upload_to='product-images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(upload_to='product-images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(upload_to='product-images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_4',
            field=models.ImageField(upload_to='product-images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_5',
            field=models.ImageField(upload_to='product-images/'),
        ),
    ]
